# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#{ config, lib, pkgs, modulesPath, ... }:
#
#{
#  imports =
#    [ (modulesPath + "/installer/scan/not-detected.nix")
#    ];
#
#  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
#  boot.initrd.kernelModules = [ ];
#  boot.kernelModules = [ "kvm-intel" ];
#  boot.extraModulePackages = [ ];
#
#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/74de096d-554f-4287-af5f-83f8e93e45d6";
#      fsType = "ext4";
#    };
#
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/AADA-8D3A";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
#    };
#
#  swapDevices = [ ];
#
#  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
#  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
#}
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f4657ee1-be57-4478-ba0c-9d7217963691";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E9F1-ADE7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
