# default
set -g prefix C-SPACE
set -g base-index 1
set -g mode-keys vi
set -g default-terminal "xterm-ghostty"
set -as terminal-overrides ",xterm-256color:RGB"
# display
set -g status-position top
set -g status-justify absolute-centre
set -g status-right ''
set -g status-left '#[fg=#1e66f5]#S '
set -g status-left-length 30
set -g pane-active-border-style "fg=blue"
set -g status-style "bg=default"
set -g window-status-style "bg=default,fg=colour250"
set -g window-status-current-style "bg=default,fg=#1e66f5"
# keymap
bind-key h if -F '#{pane_at_left}'   '' 'select-pane -L'
bind-key j if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key k if -F '#{pane_at_top}'    '' 'select-pane -U'
bind-key l if -F '#{pane_at_right}'  '' 'select-pane -R'

bind H resize-pane -L 5
bind L resize-pane -R 5
bind Enter copy-mode

bind v new-window -c "#{pane_current_path}"
bind u split-window -h -l 50% -c "#{pane_current_path}"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind g popup -d "#{pane_current_path}" -E -w 100% -h 100% "lazygit"
bind d popup -d "#{pane_current_path}" -E -w 100% -h 100% "$HOME/go/bin/devctl"
bind s popup -d "#{pane_current_path}" -E -w 100% -h 100% "lazysql"
